AR_homepage_3/config/routes.rb
Home::Application.routes.draw do

  resources :admins

get "home" => "homepage#home"

get "user" => "homepage#user"

get "map" => "homepage#map"

get "event" => "homepage#event"

get "event/:id" => "homepage#event"

get "kougi" => "homepage#kougi"

get "lab" => "homepage#lab"

get "undo" => "homepage#undo"

get "kougi1101" => "homepage#kougi1101"

get "tanakakazuaki" => "homepage#tanakakazuaki"

get "gym" => "homepage#gym"

end

AR_homepage_3/app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :name, :date, :text, :place
end

AR_homepage_3/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/new
  # GET /admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(params[:admin])

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admins/1
  # PUT /admins/1.json
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(params[:admin])
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to admins_url }
      format.json { head :no_content }
    end
  end

  before_filter :auth
  private
  def auth
    authenticate_or_request_with_http_basic do |user,pass|
      user == 'demouser' && pass == 'demodemo'
    end
  end

end

AR_homepage_3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

AR_homepage_3/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  $eve
  def home
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end 
  end
  
  def user
  end

  def map
  end

  def event
    @id = Admin.find(params[:id])
    @admins = Admin.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  def kougi
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  def lab
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  def undo
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  def kougi1101
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  def tanakakazuaki
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  def gym
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end



end

AR_homepage_3/app/helpers/admins_helper.rb
module AdminsHelper
end

AR_homepage_3/app/helpers/application_helper.rb
module ApplicationHelper
end

AR_homepage_3/app/helpers/homepage_helper.rb
module HomepageHelper
end

AR_homepage_3/app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
  イベント名<br />
  <%= f.text_field :name %>
</div>
<div class="field">
  日付<br />
  <%= f.datetime_select :date %>
</div>
<div class="field">
  内容<br />
  <%= f.text_area :text %>
</div>
<div class="field">
  施設場所<br />
<%= f.select :place, [["講義棟", "1"], ["研究棟", "2"],["運動施設", "3"]],  :prompt => "選択してください" %>
</div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AR_homepage_3/app/views/admins/edit.html.erb
<h1>イベント編集</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

AR_homepage_3/app/views/admins/index.html.erb
<table width="931" border="0" align="center" cellpadding="0" cellspacing="0" background="image/bg6.png">
<tr>
<td>

<table width="900" height="47" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td bgcolor="#000080"></td></tr>
</table>

<table width="900" height="65" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td width="438" valign="top" background="image/head5.jpg"></td>
<td width="462" > <marquee scrollamount="10" width=460><font color=red size=4>~管理者画面~</font></marquee></td></tr>
</table>

<table width="900" height="159" border="0" align="center" cellpadding="0" cellspacing="0" background="image/koho.png">
</table>

<table width="900" border="0" align="center" cellpadding="0" cellspacing="0" >
<tr><td>
<table width="700" border="0" cellpadding="0" cellspacing="0">
<tr><td height="35" background="image/title03.png">イベント管理</td></tr></table>
</td></tr></table>

<table width="900" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <th>イベント名</th>
    <th>日付</th>
    <th>内容</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.name %></td>
    <td><%= admin.date %></td>
    <td><%= admin.text %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<tr><td><br><br><%= link_to 'New Event', new_admin_path %>
<br><br><br><br><br>
</td></tr>
</table>



<table width="900" height="40" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#000080">
<tr><td align="center"><%= link_to 'HOME', {:controller => "homepage", :action => "home"}, :style => "color:white;" %></td></tr></table>



</td></tr></table>

AR_homepage_3/app/views/admins/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

AR_homepage_3/app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>イベント名：</b>
  <%= @admin.name %>
</p>
<p>
  <b>日付：</b>
  <%= @admin.date %>
</p>
<p>
  <b>内容：</b>
  <%= @admin.text %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

AR_homepage_3/app/views/homepage/event.html.erb
<tr><td><table width="900" height="300" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td width="191" valign="top" bgcolor="#B6D6F9"><br>
<table width="181" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td height="27" background="/image/side.png"><div class="side_title">イベント一覧</div></td></tr>
<tr><td>
<table>
<% @admins.each do |admin| %>
  <tr>
    <td width="600"><%= link_to admin.name, :controller => "homepage", :action => "event", :id => admin.id %></td>
</tr>
<% end %>
</table>
</td></tr>
<br>
<table width="181" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td height="27" background="/image/side.png"><div class="side_title">トピック一覧</div></td></tr>
<tr><td>
<br><br><br>
</td></tr></table>
<br>
<table width="181" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td height="27" background="/image/side.png"><div class="side_title">ニュース一覧</div></td></tr>
<tr><td>
<br><br><br>
</td></tr></table>
<br></td>
<td width="709" valign="top" align="center"><br><table width="709" border="0" align="center" cellpadding="0" cellspacing="0" style="border-color:#5FA9F9; border-width:1px; border-style:solid;">

<table width="700" border=1 bordercolor="CCFFFF">
<tr>
<td width="700" height="26" background="/image/titlebg.png"><div class="main_title"> <%= @id.name %> </div>
</td></tr>

<tr><td>
<table>
<tr><td>
<p id="notice"><%= notice %></p>

<p>
  <b>日付：</b>
  <%= @id.date %>
</p>
<p>
  <b>内容：</b>
  <%= @id.text %>
</p>

</td></tr>

</table>

</td></tr></table>

</td></tr>

AR_homepage_3/app/views/homepage/gym.html.erb
<tr><td><table width="900" height="300" border="1" bordercolor="#000080" align="center" cellpadding="0" cellspacing="0">
<tr><td width="191" valign="top" bgcolor="#FFFFFF">
<table width="190" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td><%= link_to image_tag('/image/contents.gif'), {:controller => "homepage", :action => "home"} %></td></tr>
<tr><td><%= link_to image_tag('/image/mapside.png'), {:controller => "homepage", :action => "map"} %></td></tr>
<tr><td><%= link_to image_tag('/image/kougiside.png'), {:controller => "homepage", :action => "kougi"} %></td></tr>
<tr><td><%= link_to image_tag('/image/labside.png'), {:controller => "homepage", :action => "lab"} %></td></tr>
<tr><td><%= link_to image_tag('/image/undoside.png'), {:controller => "homepage", :action => "undo"} %></td></tr>
</table>
<br></td>

<td width="709" valign="top" align="center"><br><table width="709" border="0" align="center" cellpadding="0" cellspacing="0" style="border-color:#5FA9F9; border-width:1px; border-style:solid;">

<table width="700" border=1 bordercolor="CCFFCC">
<tr><td width="700" height="26" background="/image/title_green.png"><div class="main_title"><font size="4" color="#FFFFFF"> 運動施設 </font></div>
<tr><td align="center">

<table border="0" width="150">
<tr>
<td align="center"><b style="color:#333333;">▼ 2013年9月 ▼</b></td>
</tr>
<tr>
<td><table border="0" width="150" cellpadding="2" cellspacing="1" bgcolor="#093300">
<tr align="center" bgcolor="#ededed">
<td>日</td>
<td>月</td>
<td>火</td>
<td>水</td>
<td>木</td>
<td>金</td>
<td>土</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FC0800">1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td bgcolor="#FC0800">5</td>
<td>6</td>
<td bgcolor="#FC0800">7</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FC0800">8</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
<td>13</td>
<td bgcolor="#FC0800">14</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FC0800">15</td>
<td bgcolor="#FC0800">16</td>
<td>17</td>
<td>18</td>
<td>19</td>
<td>20</td>
<td bgcolor="#FC0800">21</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FC0800">22</td>
<td bgcolor="#FC0800">23</td>
<td>24</td>
<td>25</td>
<td>26</td>
<td>27</td>
<td bgcolor="#FC0800">28</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FC0800">29</td>
<td>30</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</table></td>
</tr>
</table>


<table width="600" align="center">
<tr><td width="600" height="26" background="/image/side.png"><div class="main_title"><font size="3" color="#FFFFFF"> 運動施設一覧 </font></div>
</td></tr>
</table>
<table width="600" border=1 bordercolor="CCFFCC" align="center">
<tr><td width="150" align="center"> 1101 </td><td width="150" align="center"> 1102 </td><td width="150" align="center"> 1103 </td><td width="150" align="center"> 1104 </td></tr>
<tr><td width="150" align="center"> 2201 </td><td width="150" align="center"> 2202 </td><td width="150" align="center"> 2203 </td><td width="150" align="center"> 2204 </td></tr>
</table>
</td></tr>
</td></tr>

<tr><td width="700" height="26" background="/image/title_green.png"><div class="main_title"><font size="4" color="#FFFFFF"> イベント </font></div>
</td></tr>

<tr><td align="center">
<table>
<% @admins.each do |admin| %>

  <tr>
<% if admin.place=="1" %>
    <td width="100"><%= link_to admin.date, :controller => "homepage", :action => "event", :id => admin.id %></td>
    <td width="600"><%= link_to admin.name, :controller => "homepage", :action => "event", :id => admin.id %></td>
  </tr>
<% end %>
<% end %>
</table>
<br><br>

</td></tr></table>

</td></tr>

AR_homepage_3/app/views/homepage/home.html.erb
<tr><td><table width="900" border="1" bordercolor="#000080" align="center" cellpadding="0" cellspacing="0">
<tr><td width="191" valign="top" bgcolor="#FFFFFF">
<table width="190" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td><%= link_to image_tag('/image/contents.gif'), {:controller => "homepage", :action => "home"} %></td></tr>
<tr><td><%= link_to image_tag('/image/mapside.png'), {:controller => "homepage", :action => "map"} %></td></tr>
<tr><td><%= link_to image_tag('/image/kougiside.png'), {:controller => "homepage", :action => "kougi"} %></td></tr>
<tr><td><%= link_to image_tag('/image/labside.png'), {:controller => "homepage", :action => "lab"} %></td></tr>
<tr><td><%= link_to image_tag('/image/undoside.png'), {:controller => "homepage", :action => "undo"} %></td></tr>
</table>
<br></td>

<td width="709" valign="top"><br>
<table width="700" border="0" align="center" cellpadding="0" cellspacing="0" >
<tr>
<td height="35" background="/image/title03.png"><div class="main_title"> EVENT </div></td></tr>

<tr><td>
<table>
<% @admins.each do |admin| %>
  <tr>
    <td width="100"><%= link_to admin.date, :controller => "homepage", :action => "event", :id => admin.id %></td>
    <td width="600"><%= link_to admin.name, :controller => "homepage", :action => "event", :id => admin.id %></td>
  </tr>
<% end %>
</table>
<br><br></td></tr>

<tr>
<td height="35" background="/image/title03.png"><div class="main_title"> TOPICS </div></td></tr>

<tr><td><br><br><br><br></td></tr>

<tr>
<td height="35" background="/image/title03.png"><div class="main_title"> PRESS SCRAP </div></td></tr>

<tr><td><br><br><br><br></td></tr>

</table>

<table valign="bottom">
<tr valign="bottom">
<td width="709" valign="bottom">
<br><br><br><br><br><br><br<br>
<h2>このホームページについて</h2>
<div class="main">
・ご利用に当たり~の削除は禁止です。<br>
・マナーを守ってご利用下さい。<br>
　　など書くのかな？
</div></td></tr>
</table>

</td></tr>

AR_homepage_3/app/views/homepage/kougi.html.erb
<tr><td><table width="900" height="300" border="1" bordercolor="#000080" align="center" cellpadding="0" cellspacing="0">
<tr><td width="191" valign="top" bgcolor="#FFFFFF">
<table width="190" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td><%= link_to image_tag('/image/contents.gif'), {:controller => "homepage", :action => "home"} %></td></tr>
<tr><td><%= link_to image_tag('/image/mapside.png'), {:controller => "homepage", :action => "map"} %></td></tr>
<tr><td><%= link_to image_tag('/image/kougiside.png'), {:controller => "homepage", :action => "kougi"} %></td></tr>
<tr><td><%= link_to image_tag('/image/labside.png'), {:controller => "homepage", :action => "lab"} %></td></tr>
<tr><td><%= link_to image_tag('/image/undoside.png'), {:controller => "homepage", :action => "undo"} %></td></tr>
</table>
<br></td>


<td width="709" valign="top" align="center"><br><table width="709" border="0" align="center" cellpadding="0" cellspacing="0" style="border-color:#5FA9F9; border-width:1px; border-style:solid;">

<table width="700" border=1 bordercolor="CCFFCC">
<tr><td width="700" height="26" background="/image/title_green.png"><div class="main_title"><font size="4" color="#FFFFFF"> 講義棟 </font></div>
<tr><td align="center"><img src="/image/kougimap1.gif"><br>
→２階へ<br>
<table width="620" align="center">
<tr><td width="620" height="26" background="/image/titlebg1.png"><div class="main_title"><font size="3" color="#000000"> 講義室一覧 </font></div>
</td></tr>
</table>
<table width="600" border=1 cellspacing=0 bordercolor="#000000" align="center">
<tr><td width="150" align="center"><%= link_to "1101", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1102", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1103", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1104", {:controller => "homepage", :action => "kougi1101"} %></td></tr>
<tr><td width="150" align="center"><%= link_to "1201", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1202", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1203", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1204", {:controller => "homepage", :action => "kougi1101"} %></td></tr>
<tr><td width="150" align="center"><%= link_to "1301", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1302", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1303", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1304", {:controller => "homepage", :action => "kougi1101"} %></td></tr>
<tr><td width="150" align="center"><%= link_to "1401", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1402", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "端末講義室", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "1404", {:controller => "homepage", :action => "kougi1101"} %></td></tr>
<tr><td width="150" align="center"><%= link_to "2101", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "2102", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "2201", {:controller => "homepage", :action => "kougi1101"} %></td><td width="150" align="center"><%= link_to "500人講義室", {:controller => "homepage", :action => "kougi1101"} %></td></tr>
</table>
</td></tr>
</td></tr>

<tr><td width="700" height="26" background="/image/title_green.png"><div class="main_title"><font size="4" color="#FFFFFF"> イベント </font></div>
</td></tr>

<tr><td align="center">
<table>
<% @admins.each do |admin| %>

  <tr>
<% if admin.place=="1" %>
    <td width="100"><%= link_to admin.date, :controller => "homepage", :action => "event", :id => admin.id %></td>
    <td width="600"><%= link_to admin.name, :controller => "homepage", :action => "event", :id => admin.id %></td>
  </tr>
<% end %>
<% end %>
</table>
<br><br>

</td></tr></table>

</td></tr>

AR_homepage_3/app/views/homepage/kougi1101.html.erb
<tr><td><table width="900" height="300" border="1" bordercolor="#000080" align="center" cellpadding="0" cellspacing="0">
<tr><td width="191" valign="top" bgcolor="#FFFFFF">
<table width="190" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td><%= link_to image_tag('/image/contents.gif'), {:controller => "homepage", :action => "home"} %></td></tr>
<tr><td><%= link_to image_tag('/image/mapside.png'), {:controller => "homepage", :action => "map"} %></td></tr>
<tr><td><%= link_to image_tag('/image/kougiside.png'), {:controller => "homepage", :action => "kougi"} %></td></tr>
<tr><td><%= link_to image_tag('/image/labside.png'), {:controller => "homepage", :action => "lab"} %></td></tr>
<tr><td><%= link_to image_tag('/image/undoside.png'), {:controller => "homepage", :action => "undo"} %></td></tr>
</table>
<br></td>
<td width="709" valign="top" align="center"><br><table width="709" border="0" align="center" cellpadding="0" cellspacing="0" style="border-color:#5FA9F9; border-width:1px; border-style:solid;">

<table width="700" border=1 bordercolor="CCFFCC">
<tr><td width="700" height="26" background="/image/title_green.png"><div class="main_title"><font size="4" color="#FFFFFF"> 1201教室 </font></div>
</td></tr>
<tr><td>
<table width="620" align="center">
<tr><td width="620" height="26" background="/image/titlebg1.png"><div class="main_title"><font size="3" color="#000000"> 1201教室時限表 </font></div>
</td></tr>
</table>
<table width="600" border="1" bordercolor="#000000" align="center" bgcolor="#FFFFE0">
<tr><td width="100" align="center"></td><td width="100" align="center">１時限</td><td width="100" align="center">２時限</td><td width="100" align="center">３時限</td><td width="100" align="center">４時限</td><td width="100" align="center">５時限</td></tr>
<tr><td width="100" align="center">月曜日</td><td width="100" align="center">クラスワーク302(IIF)<br>大西　圭</td><td width="100" align="center"></td><td width="100" align="center"></td><td width="100" align="center"></td><td width="100" align="center">電子物理<br>前田　佳</td></tr>
<tr><td width="100" align="center">火曜日</td><td width="100" align="center"></td><td width="100" align="center">電磁気学Ⅱ<br>松下</td><td width="100" align="center">機械情報プロジェクトⅠ<br>許　他７名</td><td width="100" align="center">機械情報プロジェクトⅠ<br>許　他７名</td><td width="100" align="center">機械情報プロジェクトⅠ<br>許　他７名</td></tr>
<tr><td width="100" align="center">水曜日</td><td width="100" align="center"></td><td width="100" align="center">現代物理学Ⅰ<br>木内</td><td width="100" align="center">システム制御設計論<br>古賀</td><td width="100" align="center">化学Ⅰ<br>脇坂</td><td width="100" align="center"></td></tr>
<tr><td width="100" align="center">木曜日</td><td width="100" align="center"></td><td width="100" align="center"></td><td width="100" align="center">半導体工学<br>新海</td><td width="100" align="center">力学<br>許</td><td width="100" align="center"></td></tr>
<tr><td width="100" align="center">金曜日</td><td width="100" align="center"></td><td width="100" align="center">応用数学<br>福田　亮</td><td width="100" align="center">ネットワークセキュリティ<br>荒木</td><td width="100" align="center"></td><td width="100" align="center"></td></tr>
</table>
</tr></td>
<tr><td width="700" height="26" background="/image/title_green.png"><div class="main_title"><font size="4" color="#FFFFFF"> イベント </font></div>
</td></tr>

<tr><td align="center">
<table>
<% @admins.each do |admin| %>

  <tr>
<% if admin.place=="1" %>
    <td width="100"><%= link_to admin.date, :controller => "homepage", :action => "event", :id => admin.id %></td>
    <td width="600"><%= link_to admin.name, :controller => "homepage", :action => "event", :id => admin.id %></td>
  </tr>
<% end %>
<% end %>
</table>
<br><br>

</td></tr></table>

</td></tr>